# Generated by Django 4.2.30 on 2026-07-08 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('concepto', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comercio', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_recibo', models.CharField(blank=True, max_length=255, null=True)),
                ('soporte', models.TextField(blank=True, null=True)),
                ('entregado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_caja', to='caja.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Visualización', 'Visualización'), ('Operador de Módulo', 'Operador de Módulo')], default='Operador de Módulo', max_length=50)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concepto', models.TextField()),
                ('factura', models.CharField(blank=True, max_length=255, null=True)),
                ('recibo', models.CharField(blank=True, max_length=255, null=True)),
                ('reportado', models.BooleanField(default=False)),
                ('soporte', models.TextField(blank=True, null=True)),
                ('se_debe_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_pendientes', to='caja.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='EfectivoVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_entregado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concepto', models.TextField()),
                ('estado_entrega', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('soporte', models.TextField(blank=True, null=True)),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_recibidas', to='caja.colaborador')),
                ('quien_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_entregadas', to='caja.colaborador')),
            ],
        ),
    ]
